folder:
  logs: /tmp/octoprint/logs
plugins:
  cura:
    cura_engine: /bin/CuraEngine
  softwareupdate:
    _config_version: 5
    checks:
      octoprint:
        checkout_folder: /opt/octoprint/git-repo
server:
  commands:
    serverRestartCommand: /etc/init.d/octoprint restart
    systemRestartCommand: reboot
    systemShutdownCommand: poweroff

